
platform :ios, '11.0'

target 'ServiceFrameworkExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ServiceFrameworkExample
   pod "ServiceFramework", :path => "../ServiceFramework"

end
